Feature/197 use service accounts instead of dogujsons
cloudogu/cas pull request #200
Opened 2024-07-23 12:43 UTC by jelemux

Resolves #197
Resolves #193

2024-08-13 13:43 UTC, meiserloh requested changes

2024-08-13 13:43 UTC, meiserloh commented on app/src/test/java/de/triology/cas/services/RegistryEtcdTest.java
> +    @Test
is here a `expected` missing? otherwise the test has no real asserts in it

2024-08-13 13:43 UTC, meiserloh commented on app/src/test/java/de/triology/cas/services/RegistryEtcdTest.java
> +    public void getCasLogoutUriFromDoguDescriptorFallbackWithmalformedProperties() throws ParseException, GetCasLogoutUriException {
```suggestion
    public void getCasLogoutUriFromDoguDescriptorFallbackWithMalformedProperties() throws ParseException, GetCasLogoutUriException {
```

2024-08-14 07:46 UTC, jelemux commented on CHANGELOG.md
> +- Use explicit service accounts for normal CAS service accounts instead of implicitly reading dependencies. (#197)
In CES-MN _instead of_ is correct. In Classic-CES _in addition to_ is correct. Maybe we should clarify on that?

2024-08-14 07:49 UTC, meiserloh commented on CHANGELOG.md
> +- Use explicit service accounts for normal CAS service accounts instead of implicitly reading dependencies. (#197)
Yeah, that seems to be the correct move. As long as it doesn't sound like something was replaced, what is still there, I am fine with it :)

2024-08-14 08:24 UTC, jelemux commented on app/src/main/java/de/triology/cas/services/RegistryLocal.java
> +        static ServiceAccounts setDefaults(ServiceAccounts serviceAccounts) {
This is needed, because the fields can be `null` if `ServiceAccounts` is parsed from YAML.

2024-08-14 08:30 UTC, meiserloh commented on app/src/main/java/de/triology/cas/services/RegistryLocal.java
> +        static ServiceAccounts setDefaults(ServiceAccounts serviceAccounts) {
Crazy that this actually happens the way the code is written. But okay :)

2024-08-14 08:30 UTC, jelemux commented on resources/post-upgrade.sh
> +      doguctl config "service_accounts/${saType}/${service}/secret" "${clientSecretHash}"
I don't think this is possible as ETCD distinguishes between files and directories and it's not possible to have both.

2024-08-14 08:35 UTC, meiserloh commented on resources/post-upgrade.sh
> +      doguctl config "service_accounts/${saType}/${service}/secret" "${clientSecretHash}"
oh you're right, I missed that

2024-08-14 12:00 UTC, meiserloh commented
When testing I get the following error in the cas logs (for portainer and teamscale):
```
2024-08-14 12:07:15,377 ERROR [org.apereo.cas.authentication.principal.AbstractServiceFactory] - <Unable to extract query parameters from [https://((?i)192\.168\.56\.2)(:443)?/teamscale(/.*)?]: [java.net.URISyntaxException: Illegal character in query at index 16: https://((?i)192\.168\.56\.2)(:443)?/teamscale(/.*)?]>
```
The tests were: log in, log out from dogu, check dogu via warp menu, if still logged in, log in, log out via warp menu, check if still logged in.

2024-08-20 06:29 UTC, merged